//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKU.Arsiv.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArsiv
    {
        public long No { get; set; }
        public string Grup1 { get; set; }
        public string Grup2 { get; set; }
        public string Grup3 { get; set; }
        public string Grup4 { get; set; }
        public string Sira { get; set; }
        public string Tarih { get; set; }
        public string Sayi { get; set; }
        public string Konu { get; set; }
        public Nullable<int> Sayfa { get; set; }
        public string Aciklama { get; set; }
    }
}
